// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

#include "types.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace DRPB {
}  // namespace DRPB
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_types_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_types_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_types_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_types_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_types_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013types.proto\022\004DRPB*\253\004\n\010DataType\022\020\n\014DRPB"
  "_INVALID\020\000\022\020\n\014DRPB_NPY_INT\020\001\022\021\n\rDRPB_NPY"
  "_UINT\020\002\022\021\n\rDRPB_NPY_LONG\020\003\022\022\n\016DRPB_NPY_U"
  "LONG\020\004\022\025\n\021DRPB_NPY_LONGLONG\020\005\022\026\n\022DRPB_NP"
  "Y_ULONGLONG\020\006\022\022\n\016DRPB_NPY_FLOAT\020\007\022\023\n\017DRP"
  "B_NPY_DOUBLE\020\010\022\023\n\017DRPB_NPY_STRING\020\t\022\021\n\rD"
  "RPB_NPY_BOOL\020\n\022\021\n\rDRPB_NPY_BYTE\020\013\022\022\n\016DRP"
  "B_NPY_UBYTE\020\014\022\022\n\016DRPB_NPY_SHORT\020\r\022\023\n\017DRP"
  "B_NPY_USHORT\020\016\022\027\n\023DRPB_NPY_LONGDOUBLE\020\017\022"
  "\030\n\024DRPB_NPY_CLONGDOUBLE\020\020\022\023\n\017DRPB_NPY_OB"
  "JECT\020\021\022\024\n\020DRPB_NPY_UNICODE\020\022\022\021\n\rDRPB_NPY"
  "_VOID\020\023\022\025\n\021DRPB_NPY_DATETIME\020\024\022\026\n\022DRPB_N"
  "PY_TIMEDELTA\020\025\022\021\n\rDRPB_NPY_HALF\020\026\022\023\n\017DRP"
  "B_NPY_NTYPES\020\027\022\023\n\017DRPB_NPY_NOTYPE\020\030\022\024\n\020D"
  "RPB_NPY_USERDEF\020\031b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_types_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_types_2eproto = {
  false, false, 585, descriptor_table_protodef_types_2eproto, "types.proto", 
  &descriptor_table_types_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_types_2eproto::offsets,
  file_level_metadata_types_2eproto, file_level_enum_descriptors_types_2eproto, file_level_service_descriptors_types_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_types_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_types_2eproto);
  return descriptor_table_types_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_types_2eproto(&descriptor_table_types_2eproto);
namespace DRPB {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_types_2eproto);
  return file_level_enum_descriptors_types_2eproto[0];
}
bool DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace DRPB
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
